package Hibernate.objecte;
// Generated 28.10.2013 11:53:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bestellung generated by hbm2java
 */
public class Bestellung  implements java.io.Serializable {


     private Integer bestellungId;
     private Benutzer benutzer;
     private Kunde kunde;
     private Date datum;
     private Set kartes = new HashSet(0);

    public Bestellung() {
    }

	
    public Bestellung(Benutzer benutzer, Kunde kunde, Date datum) {
        this.benutzer = benutzer;
        this.kunde = kunde;
        this.datum = datum;
    }
    public Bestellung(Benutzer benutzer, Kunde kunde, Date datum, Set kartes) {
       this.benutzer = benutzer;
       this.kunde = kunde;
       this.datum = datum;
       this.kartes = kartes;
    }
   
    public Integer getBestellungId() {
        return this.bestellungId;
    }
    
    public void setBestellungId(Integer bestellungId) {
        this.bestellungId = bestellungId;
    }
    public Benutzer getBenutzer() {
        return this.benutzer;
    }
    
    public void setBenutzer(Benutzer benutzer) {
        this.benutzer = benutzer;
    }
    public Kunde getKunde() {
        return this.kunde;
    }
    
    public void setKunde(Kunde kunde) {
        this.kunde = kunde;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public Set getKartes() {
        return this.kartes;
    }
    
    public void setKartes(Set kartes) {
        this.kartes = kartes;
    }




}


