package Hibernate.objecte;
// Generated 28.10.2013 11:53:03 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
public class Genre  implements java.io.Serializable {


     private Integer genreId;
     private String name;
     private String beschreibung;
     private Set kuenstlers = new HashSet(0);

    public Genre() {
    }

	
    public Genre(String name) {
        this.name = name;
    }
    public Genre(String name, String beschreibung, Set kuenstlers) {
       this.name = name;
       this.beschreibung = beschreibung;
       this.kuenstlers = kuenstlers;
    }
   
    public Integer getGenreId() {
        return this.genreId;
    }
    
    public void setGenreId(Integer genreId) {
        this.genreId = genreId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }
    public Set getKuenstlers() {
        return this.kuenstlers;
    }
    
    public void setKuenstlers(Set kuenstlers) {
        this.kuenstlers = kuenstlers;
    }




}


