package Hibernate.objecte;
// Generated 28.10.2013 11:53:03 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Kartenstatus generated by hbm2java
 */
public class Kartenstatus  implements java.io.Serializable {


     private Integer kartenstatusId;
     private String name;
     private String beschreibung;
     private Set kartes = new HashSet(0);

    public Kartenstatus() {
    }

	
    public Kartenstatus(String name) {
        this.name = name;
    }
    public Kartenstatus(String name, String beschreibung, Set kartes) {
       this.name = name;
       this.beschreibung = beschreibung;
       this.kartes = kartes;
    }
   
    public Integer getKartenstatusId() {
        return this.kartenstatusId;
    }
    
    public void setKartenstatusId(Integer kartenstatusId) {
        this.kartenstatusId = kartenstatusId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }
    public Set getKartes() {
        return this.kartes;
    }
    
    public void setKartes(Set kartes) {
        this.kartes = kartes;
    }




}


