package Hibernate.objecte;
// Generated 28.10.2013 11:53:03 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Karte generated by hbm2java
 */
public class Karte  implements java.io.Serializable {


     private Integer kartenId;
     private Bestellung bestellung;
     private Kartenstatus kartenstatus;
     private Kategorie kategorie;
     private String name;
     private String beschreibung;
     private Integer sitzplatz;
     private String reihe;
     private BigDecimal preis;
     private Boolean ermaessigt;

    public Karte() {
    }

	
    public Karte(Kartenstatus kartenstatus, Kategorie kategorie, String name) {
        this.kartenstatus = kartenstatus;
        this.kategorie = kategorie;
        this.name = name;
    }
    public Karte(Bestellung bestellung, Kartenstatus kartenstatus, Kategorie kategorie, String name, String beschreibung, Integer sitzplatz, String reihe, BigDecimal preis, Boolean ermaessigt) {
       this.bestellung = bestellung;
       this.kartenstatus = kartenstatus;
       this.kategorie = kategorie;
       this.name = name;
       this.beschreibung = beschreibung;
       this.sitzplatz = sitzplatz;
       this.reihe = reihe;
       this.preis = preis;
       this.ermaessigt = ermaessigt;
    }
   
    public Integer getKartenId() {
        return this.kartenId;
    }
    
    public void setKartenId(Integer kartenId) {
        this.kartenId = kartenId;
    }
    public Bestellung getBestellung() {
        return this.bestellung;
    }
    
    public void setBestellung(Bestellung bestellung) {
        this.bestellung = bestellung;
    }
    public Kartenstatus getKartenstatus() {
        return this.kartenstatus;
    }
    
    public void setKartenstatus(Kartenstatus kartenstatus) {
        this.kartenstatus = kartenstatus;
    }
    public Kategorie getKategorie() {
        return this.kategorie;
    }
    
    public void setKategorie(Kategorie kategorie) {
        this.kategorie = kategorie;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }
    public Integer getSitzplatz() {
        return this.sitzplatz;
    }
    
    public void setSitzplatz(Integer sitzplatz) {
        this.sitzplatz = sitzplatz;
    }
    public String getReihe() {
        return this.reihe;
    }
    
    public void setReihe(String reihe) {
        this.reihe = reihe;
    }
    public BigDecimal getPreis() {
        return this.preis;
    }
    
    public void setPreis(BigDecimal preis) {
        this.preis = preis;
    }
    public Boolean getErmaessigt() {
        return this.ermaessigt;
    }
    
    public void setErmaessigt(Boolean ermaessigt) {
        this.ermaessigt = ermaessigt;
    }




}


