package Hibernate.objecte;
// Generated 28.10.2013 11:53:03 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Kuenstler generated by hbm2java
 */
public class Kuenstler  implements java.io.Serializable {


     private Integer kuenstlerId;
     private String name;
     private String beschreibung;
     private Set genres = new HashSet(0);
     private Set veranstaltungs = new HashSet(0);

    public Kuenstler() {
    }

	
    public Kuenstler(String name) {
        this.name = name;
    }
    public Kuenstler(String name, String beschreibung, Set genres, Set veranstaltungs) {
       this.name = name;
       this.beschreibung = beschreibung;
       this.genres = genres;
       this.veranstaltungs = veranstaltungs;
    }
   
    public Integer getKuenstlerId() {
        return this.kuenstlerId;
    }
    
    public void setKuenstlerId(Integer kuenstlerId) {
        this.kuenstlerId = kuenstlerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }
    public Set getGenres() {
        return this.genres;
    }
    
    public void setGenres(Set genres) {
        this.genres = genres;
    }
    public Set getVeranstaltungs() {
        return this.veranstaltungs;
    }
    
    public void setVeranstaltungs(Set veranstaltungs) {
        this.veranstaltungs = veranstaltungs;
    }




}


