package Hibernate.objecte;
// Generated 28.10.2013 11:53:03 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rolle generated by hbm2java
 */
public class Rolle  implements java.io.Serializable {


     private Integer rolleId;
     private String name;
     private String beschreibung;
     private Set benutzers = new HashSet(0);

    public Rolle() {
    }

	
    public Rolle(String name) {
        this.name = name;
    }
    public Rolle(String name, String beschreibung, Set benutzers) {
       this.name = name;
       this.beschreibung = beschreibung;
       this.benutzers = benutzers;
    }
   
    public Integer getRolleId() {
        return this.rolleId;
    }
    
    public void setRolleId(Integer rolleId) {
        this.rolleId = rolleId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }
    public Set getBenutzers() {
        return this.benutzers;
    }
    
    public void setBenutzers(Set benutzers) {
        this.benutzers = benutzers;
    }




}


