package Hibernate.objecte;
// Generated 28.10.2013 11:53:03 by Hibernate Tools 3.2.1.GA



/**
 * Tournee generated by hbm2java
 */
public class Tournee  implements java.io.Serializable {


     private Integer tourneeId;
     private String name;
     private String beschreibung;

    public Tournee() {
    }

	
    public Tournee(String name) {
        this.name = name;
    }
    public Tournee(String name, String beschreibung) {
       this.name = name;
       this.beschreibung = beschreibung;
    }
   
    public Integer getTourneeId() {
        return this.tourneeId;
    }
    
    public void setTourneeId(Integer tourneeId) {
        this.tourneeId = tourneeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }




}


