package Hibernate.objecte;
// Generated 28.10.2013 11:53:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Veranstaltung generated by hbm2java
 */
public class Veranstaltung  implements java.io.Serializable {


     private Integer veranstaltungId;
     private Veranstaltungstyp veranstaltungstyp;
     private Veranstaltungsort veranstaltungsort;
     private Veranstalter veranstalter;
     private String name;
     private String beschreibung;
     private Date datumUhrzeit;
     private int ermaessigung;
     private Integer tourneeId;
     private Set kategories = new HashSet(0);
     private Set kuenstlers = new HashSet(0);

    public Veranstaltung() {
    }

	
    public Veranstaltung(Veranstaltungstyp veranstaltungstyp, Veranstaltungsort veranstaltungsort, Veranstalter veranstalter, String name, Date datumUhrzeit, int ermaessigung) {
        this.veranstaltungstyp = veranstaltungstyp;
        this.veranstaltungsort = veranstaltungsort;
        this.veranstalter = veranstalter;
        this.name = name;
        this.datumUhrzeit = datumUhrzeit;
        this.ermaessigung = ermaessigung;
    }
    public Veranstaltung(Veranstaltungstyp veranstaltungstyp, Veranstaltungsort veranstaltungsort, Veranstalter veranstalter, String name, String beschreibung, Date datumUhrzeit, int ermaessigung, Integer tourneeId, Set kategories, Set kuenstlers) {
       this.veranstaltungstyp = veranstaltungstyp;
       this.veranstaltungsort = veranstaltungsort;
       this.veranstalter = veranstalter;
       this.name = name;
       this.beschreibung = beschreibung;
       this.datumUhrzeit = datumUhrzeit;
       this.ermaessigung = ermaessigung;
       this.tourneeId = tourneeId;
       this.kategories = kategories;
       this.kuenstlers = kuenstlers;
    }
   
    public Integer getVeranstaltungId() {
        return this.veranstaltungId;
    }
    
    public void setVeranstaltungId(Integer veranstaltungId) {
        this.veranstaltungId = veranstaltungId;
    }
    public Veranstaltungstyp getVeranstaltungstyp() {
        return this.veranstaltungstyp;
    }
    
    public void setVeranstaltungstyp(Veranstaltungstyp veranstaltungstyp) {
        this.veranstaltungstyp = veranstaltungstyp;
    }
    public Veranstaltungsort getVeranstaltungsort() {
        return this.veranstaltungsort;
    }
    
    public void setVeranstaltungsort(Veranstaltungsort veranstaltungsort) {
        this.veranstaltungsort = veranstaltungsort;
    }
    public Veranstalter getVeranstalter() {
        return this.veranstalter;
    }
    
    public void setVeranstalter(Veranstalter veranstalter) {
        this.veranstalter = veranstalter;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }
    public Date getDatumUhrzeit() {
        return this.datumUhrzeit;
    }
    
    public void setDatumUhrzeit(Date datumUhrzeit) {
        this.datumUhrzeit = datumUhrzeit;
    }
    public int getErmaessigung() {
        return this.ermaessigung;
    }
    
    public void setErmaessigung(int ermaessigung) {
        this.ermaessigung = ermaessigung;
    }
    public Integer getTourneeId() {
        return this.tourneeId;
    }
    
    public void setTourneeId(Integer tourneeId) {
        this.tourneeId = tourneeId;
    }
    public Set getKategories() {
        return this.kategories;
    }
    
    public void setKategories(Set kategories) {
        this.kategories = kategories;
    }
    public Set getKuenstlers() {
        return this.kuenstlers;
    }
    
    public void setKuenstlers(Set kuenstlers) {
        this.kuenstlers = kuenstlers;
    }




}


