package Hibernate.objecte;
// Generated 28.10.2013 11:53:03 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Veranstaltungstyp generated by hbm2java
 */
public class Veranstaltungstyp  implements java.io.Serializable {


     private Integer veranstaltungstypId;
     private String name;
     private String beschreibung;
     private Set veranstaltungs = new HashSet(0);

    public Veranstaltungstyp() {
    }

	
    public Veranstaltungstyp(String name) {
        this.name = name;
    }
    public Veranstaltungstyp(String name, String beschreibung, Set veranstaltungs) {
       this.name = name;
       this.beschreibung = beschreibung;
       this.veranstaltungs = veranstaltungs;
    }
   
    public Integer getVeranstaltungstypId() {
        return this.veranstaltungstypId;
    }
    
    public void setVeranstaltungstypId(Integer veranstaltungstypId) {
        this.veranstaltungstypId = veranstaltungstypId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }
    public Set getVeranstaltungs() {
        return this.veranstaltungs;
    }
    
    public void setVeranstaltungs(Set veranstaltungs) {
        this.veranstaltungs = veranstaltungs;
    }




}


